# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: openiddictexample.sln
services:
- name: openiddictexample
  project: OpenIdDictExample/OpenIdDictExample.csproj
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2019-latest 
  env:
  - name: sa
    value: "admin"
  - name: ACCEPT_EULA
    value: 'Y'
  volumes:
  - name: vote-storage
    target: /var/opt/mssql
